### ISSUE TITLE
Critter returning empty responses, and JDCB exceptions in the logs

### ISSUE THREAD

**Issue by pvdissel** [emicklei/critter#22]
After a while of usage, somehow the responses of Critter became empty. While it worked locally when testing against a newly started Critter.

The following exceptions came up in the Critter logs when the empty responses started:

```
Apr 19, 2016 7:31:46 PM org.jboss.netty.channel.SimpleChannelUpstreamHandler
WARNING: EXCEPTION, please implement com.sun.jersey.server.impl.container.netty.NettyHandlerContainer.exceptionCaught() for proper handling.
org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 65536 bytes.
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:168)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:448)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:538)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:437)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:91)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:373)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:247)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Apr 20, 2016 1:04:23 AM org.jboss.netty.channel.SimpleChannelUpstreamHandler
WARNING: EXCEPTION, please implement com.sun.jersey.server.impl.container.netty.NettyHandlerContainer.exceptionCaught() for proper handling.
com.philemonworks.critter.dao.sql.support.SqlRuntimeException: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: org.h2.jdbc.JdbcSQLException: IO Exception: ""Missing lob entry: 4"" [90028-174]"; "lob: null table: -1 id: 4" [90031-174]
	at com.philemonworks.critter.dao.sql.support.JdbcTemplate.queryForList(JdbcTemplate.java:65)
	at com.philemonworks.critter.dao.sql.RuleDaoSqlImpl.getRules(RuleDaoSqlImpl.java:40)
	at com.philemonworks.critter.TrafficManager.detectRule(TrafficManager.java:16)
	at com.philemonworks.critter.ProxyResource.detectAndApplyRule(ProxyResource.java:98)
	at com.philemonworks.critter.ProxyResource.performActionsFor(ProxyResource.java:89)
	at com.philemonworks.critter.ProxyResource.handleGet(ProxyResource.java:53)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
	at com.sun.jersey.server.impl.container.netty.NettyHandlerContainer.messageReceived(NettyHandlerContainer.java:123)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:149)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:455)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:538)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:437)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:91)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:373)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:247)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: org.h2.jdbc.JdbcSQLException: IO Exception: ""Missing lob entry: 4"" [90028-174]"; "lob: null table: -1 id: 4" [90031-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:161)
	at org.h2.message.DbException.convertIOException(DbException.java:318)
	at org.h2.value.ValueLobDb.getInputStream(ValueLobDb.java:412)
	at org.h2.value.ValueLobDb.getReader(ValueLobDb.java:395)
	at org.h2.value.ValueLobDb.getString(ValueLobDb.java:310)
	at org.h2.jdbc.JdbcClob.getAsciiStream(JdbcClob.java:87)
	at com.philemonworks.critter.Utils.clobToString(Utils.java:69)
	at com.philemonworks.critter.dao.sql.RuleDaoSqlImpl$RuleMapper.map(RuleDaoSqlImpl.java:90)
	at com.philemonworks.critter.dao.sql.RuleDaoSqlImpl$RuleMapper.map(RuleDaoSqlImpl.java:87)
	at com.philemonworks.critter.dao.sql.support.JdbcTemplate.queryForList(JdbcTemplate.java:62)
	... 34 more
Caused by: java.io.IOException: org.h2.jdbc.JdbcSQLException: IO Exception: "Missing lob entry: 4" [90028-174]
	at org.h2.message.DbException.convertToIOException(DbException.java:351)
	at org.h2.store.LobStorageBackend.getInputStream(LobStorageBackend.java:345)
	at org.h2.value.ValueLobDb.getInputStream(ValueLobDb.java:410)
	... 41 more
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "Missing lob entry: 4" [90028-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.store.LobStorageBackend$LobInputStream.<init>(LobStorageBackend.java:658)
	at org.h2.store.LobStorageBackend.getInputStream(LobStorageBackend.java:341)
	... 42 more
```

So far no re-production path...

**Comment by pvdissel** [comment]
The exception occures a few minutes after the user tests have finished running...

**Comment by emicklei** [comment]
such an exception often indicates a corrupt DB. we will investigate
